"""Curated topics + scripts for TalkFlow."""

TOPICS = [
    # ===== Everyday English =====
    {
        "id": "everyday-introducing-yourself",
        "category": "Everyday English",
        "title": "Introducing Yourself",
        "description": "Practice a warm, clear self-introduction for casual meetings.",
        "difficulty": "beginner",
        "duration_min": 3,
        "sentences": [
            "Hi, my name is Alex. It is really nice to meet you.",
            "I grew up in a small coastal town, but I moved to the city a few years ago.",
            "These days I work in design, and I love how it lets me solve problems visually.",
            "In my free time, I like hiking, reading, and trying out new coffee shops.",
            "One thing people are often surprised to learn about me is that I can juggle.",
            "I am really glad we get a chance to talk today.",
        ],
    },
    {
        "id": "everyday-small-talk",
        "category": "Everyday English",
        "title": "Small Talk with a Neighbor",
        "description": "Light, friendly exchanges perfect for daily situations.",
        "difficulty": "beginner",
        "duration_min": 3,
        "sentences": [
            "Good morning. How is your day going so far?",
            "The weather has been really unpredictable this week, hasn't it?",
            "I saw you were doing some work on the garden. It looks great.",
            "By the way, did you catch that new bakery that opened on the corner?",
            "We should grab a coffee there sometime.",
            "Anyway, have a wonderful day. See you soon.",
        ],
    },
    {
        "id": "everyday-ordering-coffee",
        "category": "Everyday English",
        "title": "Ordering at a Cafe",
        "description": "Order confidently and handle common follow-up questions.",
        "difficulty": "beginner",
        "duration_min": 2,
        "sentences": [
            "Hi, could I please have a medium oat milk latte?",
            "Actually, could you make that a little less sweet than usual?",
            "I would also like one of the almond croissants, please.",
            "Is it possible to have that warmed up?",
            "That's everything, thanks. I'll take it to go.",
            "Thank you so much. Have a great day.",
        ],
    },
    {
        "id": "everyday-asking-directions",
        "category": "Everyday English",
        "title": "Asking for Directions",
        "description": "Ask politely and confirm what you heard.",
        "difficulty": "beginner",
        "duration_min": 2,
        "sentences": [
            "Excuse me, sorry to bother you. Could you help me for a moment?",
            "I'm trying to find the nearest subway station.",
            "Am I close, or do I need to head in a different direction?",
            "So I go straight two blocks and then turn right at the traffic light?",
            "Great, that makes sense. Is it walkable from here?",
            "Thank you so much for your help. Have a nice day.",
        ],
    },
    {
        "id": "everyday-phone-call",
        "category": "Everyday English",
        "title": "Making a Phone Reservation",
        "description": "A short, polished phone call to book a table.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Hello, I'd like to make a reservation for this Friday, please.",
            "I'd like a table for four at around seven in the evening.",
            "Do you have anything available closer to the window if possible?",
            "One person in our group has a nut allergy. Would that be an issue?",
            "Perfect. The reservation is under the name Morgan.",
            "Thank you so much for your help. See you Friday.",
        ],
    },

    # ===== Career & Job Interviews =====
    {
        "id": "career-tell-me-about-yourself",
        "category": "Career & Job Interviews",
        "title": "Tell Me About Yourself",
        "description": "The classic opener, structured for confidence and clarity.",
        "difficulty": "intermediate",
        "duration_min": 4,
        "sentences": [
            "Thanks for having me today. I'm excited to be here.",
            "I'm a product designer with about five years of experience.",
            "I started my career at a small startup, where I learned to wear many hats.",
            "Most recently, I led the redesign of a mobile onboarding flow that lifted activation by 22 percent.",
            "What draws me to this role is your team's focus on thoughtful, human-centered design.",
            "I'd love to bring my experience to a company that clearly values craft.",
        ],
    },
    {
        "id": "career-strengths-weaknesses",
        "category": "Career & Job Interviews",
        "title": "Strengths and Weaknesses",
        "description": "Answer honestly without over-selling or over-apologizing.",
        "difficulty": "intermediate",
        "duration_min": 4,
        "sentences": [
            "One of my key strengths is turning ambiguity into clear next steps.",
            "For example, when a project stalled last quarter, I mapped out the blockers and got us shipping again.",
            "In terms of a weakness, I sometimes take on too much myself before delegating.",
            "I've been working on this by holding weekly check-ins and trusting the team more.",
            "It has made a real difference and freed me up to focus on higher leverage work.",
            "I think self-awareness is the first step, and I'm committed to continuing to grow.",
        ],
    },
    {
        "id": "career-why-this-company",
        "category": "Career & Job Interviews",
        "title": "Why This Company?",
        "description": "Show genuine research and alignment with the mission.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "I've been following your company for a while, especially after your last product launch.",
            "What stands out to me is how you balance rapid growth with a strong sense of user care.",
            "I also read a recent interview with your CEO about long-term thinking, and it really resonated with me.",
            "I'd bring both my technical skills and a deep interest in your customer segment.",
            "For me, this isn't just another job. It feels like the right next step.",
            "I'd be genuinely excited to contribute here.",
        ],
    },
    {
        "id": "career-salary-negotiation",
        "category": "Career & Job Interviews",
        "title": "Salary Negotiation",
        "description": "Discuss compensation with confidence and warmth.",
        "difficulty": "advanced",
        "duration_min": 3,
        "sentences": [
            "Thanks for sharing the offer. I appreciate the thought that went into it.",
            "Based on my research for this role and my experience, I was expecting a base closer to a certain range.",
            "Is there flexibility on the base salary, or perhaps on the signing bonus?",
            "I'm also open to exploring equity or additional vacation time.",
            "I want to make this work because I'm genuinely excited about the role.",
            "What do you think would be possible from your side?",
        ],
    },

    # ===== Travel =====
    {
        "id": "travel-airport-checkin",
        "category": "Travel",
        "title": "At the Airport Check-in",
        "description": "Handle check-in smoothly, including small requests.",
        "difficulty": "beginner",
        "duration_min": 2,
        "sentences": [
            "Good morning. I'd like to check in for my flight to Barcelona, please.",
            "Here is my passport and booking confirmation.",
            "I have one checked bag and one carry-on today.",
            "Is it possible to get a window seat, ideally toward the front?",
            "Great, thanks. What time does boarding start?",
            "Thank you so much. Have a wonderful day.",
        ],
    },
    {
        "id": "travel-hotel-check-in",
        "category": "Travel",
        "title": "Hotel Check-in and Requests",
        "description": "Check in and politely ask for room upgrades or amenities.",
        "difficulty": "beginner",
        "duration_min": 3,
        "sentences": [
            "Hello, I have a reservation under the name Rivera for three nights.",
            "Just to double-check, that includes breakfast, right?",
            "Would it be possible to have a higher floor with a quieter view?",
            "Could I also request a late check-out on the last day, if possible?",
            "One more thing, could you recommend a good local place for dinner tonight?",
            "Thank you so much. This is really helpful.",
        ],
    },
    {
        "id": "travel-lost-luggage",
        "category": "Travel",
        "title": "Reporting Lost Luggage",
        "description": "Stay calm and clear when things go wrong.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Hi, I just landed and I can't seem to find my suitcase on the carousel.",
            "Here is my baggage tag and my boarding pass.",
            "It's a medium sized dark blue hard-shell suitcase with a bright yellow ribbon.",
            "Could you check whether it might have been delayed or misrouted?",
            "I'll be staying at the Grand Plaza hotel for the next four nights.",
            "What is the best way for me to follow up if I don't hear back today?",
        ],
    },

    # ===== Academic English =====
    {
        "id": "academic-presentation-intro",
        "category": "Academic English",
        "title": "Opening an Academic Presentation",
        "description": "Set the stage with a clear thesis and roadmap.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Good afternoon everyone, and thank you for being here today.",
            "In this presentation, I'll be exploring the impact of remote learning on student engagement.",
            "I'll begin by outlining the key challenges observed in the past few years.",
            "Then, I'll walk you through the data we collected from three universities.",
            "Finally, I'll share our recommendations for hybrid learning environments.",
            "Please feel free to interrupt with questions at any point.",
        ],
    },
    {
        "id": "academic-agree-disagree",
        "category": "Academic English",
        "title": "Agreeing and Disagreeing in a Seminar",
        "description": "Push back respectfully and build on others' ideas.",
        "difficulty": "advanced",
        "duration_min": 4,
        "sentences": [
            "That's a really interesting point, and I want to build on it.",
            "I agree that the historical context matters more than we often admit.",
            "However, I'd push back a little on the second part of your argument.",
            "The evidence from the 2019 study seems to suggest a different pattern.",
            "It might be that both effects are happening at the same time.",
            "I'd love to hear what others think about this.",
        ],
    },
    {
        "id": "academic-thesis-defense",
        "category": "Academic English",
        "title": "Thesis Defense Q&A",
        "description": "Handle tough questions with grace and precision.",
        "difficulty": "advanced",
        "duration_min": 4,
        "sentences": [
            "Thank you for the question. It gets to the heart of my methodology.",
            "I chose a mixed-methods approach because purely quantitative work missed the nuance.",
            "You're right that the sample size is a limitation of this study.",
            "In future work, I would broaden the participant pool and diversify recruitment.",
            "That said, the findings still point to a consistent pattern across all three cohorts.",
            "I'd be happy to walk through the statistical significance in more detail.",
        ],
    },

    # ===== Workplace Communication =====
    {
        "id": "workplace-standup",
        "category": "Workplace Communication",
        "title": "Daily Standup Update",
        "description": "Share progress, blockers, and next steps concisely.",
        "difficulty": "beginner",
        "duration_min": 2,
        "sentences": [
            "Good morning team. Here's a quick update from my side.",
            "Yesterday, I wrapped up the user research report and shared it in the channel.",
            "Today, I'll be reviewing the design proposals from the vendor.",
            "The only blocker I have is waiting on final approval from legal.",
            "If anyone has capacity to help unblock that, I'd really appreciate it.",
            "That's all from me. Back to you.",
        ],
    },
    {
        "id": "workplace-feedback",
        "category": "Workplace Communication",
        "title": "Giving Constructive Feedback",
        "description": "Feedback that lands well and moves work forward.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Thanks for making time to chat. I wanted to share some thoughts on last week's launch.",
            "Overall, I thought the execution was really strong, especially the onboarding flow.",
            "One area I'd like to explore is how we're handling stakeholder communication.",
            "There were a couple of moments where updates could have been more proactive.",
            "For next time, could we set up a shared timeline that everyone can see?",
            "I'm sharing this because I trust your judgment and want us to keep improving together.",
        ],
    },
    {
        "id": "workplace-disagree-politely",
        "category": "Workplace Communication",
        "title": "Disagreeing with Your Manager",
        "description": "Advocate for your perspective while staying collaborative.",
        "difficulty": "advanced",
        "duration_min": 3,
        "sentences": [
            "I appreciate you sharing the direction. I want to be transparent about some concerns.",
            "From what I'm seeing on the ground, this timeline may be tighter than it looks.",
            "I'm worried that rushing could impact quality in a way that's hard to recover from.",
            "Could we explore shipping a smaller scope first and expanding in a fast follow?",
            "I'm fully committed to whatever we decide, I just wanted to raise this early.",
            "What's your take on the trade-offs?",
        ],
    },
    {
        "id": "workplace-explaining-tech",
        "category": "Workplace Communication",
        "title": "Explaining a Technical Concept",
        "description": "Make complex ideas simple for non-technical stakeholders.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Let me walk you through this in plain language.",
            "Think of the database as a giant, well-organized filing cabinet.",
            "Every time a user takes an action, we file that away as a small note.",
            "The problem right now is that we're opening the same drawer thousands of times a minute.",
            "The fix is essentially to keep the most-used drawer open, which makes everything faster.",
            "Happy to go deeper if you want, but that's the core idea.",
        ],
    },

    # ===== Presentations =====
    {
        "id": "presentations-elevator-pitch",
        "category": "Presentations",
        "title": "Elevator Pitch",
        "description": "Sell your idea or product in under a minute.",
        "difficulty": "intermediate",
        "duration_min": 2,
        "sentences": [
            "Imagine spending less than five minutes a day to feel more confident speaking English.",
            "That's exactly what TalkFlow does for busy professionals around the world.",
            "It's a karaoke-style practice studio that builds fluency through real, everyday scripts.",
            "We're already helping thousands of learners speak with more clarity and less anxiety.",
            "What sets us apart is our focus on rhythm, pacing, and confidence, not just grammar.",
            "I'd love to show you a quick demo. Do you have a moment?",
        ],
    },
    {
        "id": "presentations-product-demo",
        "category": "Presentations",
        "title": "Product Demo Opening",
        "description": "Frame the value clearly before showing screens.",
        "difficulty": "intermediate",
        "duration_min": 3,
        "sentences": [
            "Before I show you the product, I want to share the problem we're solving.",
            "Most language learners get stuck because they don't get enough time to actually speak.",
            "Textbooks and quizzes can't replace real speaking practice.",
            "That's the gap our product fills, with guided scripts and immediate progress feedback.",
            "In the next three minutes, I'll walk you through a real practice session.",
            "By the end, you'll see exactly how it feels for our users.",
        ],
    },
    {
        "id": "presentations-closing",
        "category": "Presentations",
        "title": "Confident Closing and Call to Action",
        "description": "End on a strong, memorable note.",
        "difficulty": "advanced",
        "duration_min": 2,
        "sentences": [
            "So to bring it all together, we've walked through the problem, the solution, and the results.",
            "The pattern is clear: consistent practice leads to real, measurable progress.",
            "Our mission is to make speaking practice as easy as pressing play.",
            "If you believe in that vision, I'd love to explore what a partnership could look like.",
            "We have room in our next cohort, and I'd be delighted to hold a spot for your team.",
            "Thank you for your time. I'm happy to take questions.",
        ],
    },
    {
        "id": "presentations-storytelling",
        "category": "Presentations",
        "title": "Opening with a Story",
        "description": "Hook the audience with a personal moment.",
        "difficulty": "advanced",
        "duration_min": 3,
        "sentences": [
            "A few years ago, I stood in front of a room and completely froze.",
            "I had prepared for weeks, but the words just wouldn't come out.",
            "I promised myself I'd never feel that way again.",
            "So I started practicing every single day, even if only for five minutes.",
            "That's the moment that eventually led me to build what I'm about to show you.",
            "Because I believe no one should ever feel that way when they have something important to say.",
        ],
    },
]

FREE_PROMPTS = [
    "Describe your favorite place to visit and why it matters to you.",
    "Talk about a book or movie that changed the way you think.",
    "If you could learn any new skill in a week, what would it be and why?",
    "Describe your ideal weekend from morning to night.",
    "Explain a small habit that has made a big difference in your life.",
    "Talk about a memorable meal you had and who was there.",
    "If you were to give one piece of advice to your younger self, what would it be?",
    "Describe your dream job and what a perfect day in that role would look like.",
    "Talk about a time you overcame a challenge you didn't think you could.",
    "Describe your hometown to someone who has never been there.",
]
